import type { SimpleIcon } from "simple-icons";
import {
  siAlmalinux, siAlpinelinux, siAmd, siAnsible, siApache, siApachekafka, siApachetomcat,
  siArgo, siArm, siBroadcom, siCentos, siCeph, siCilium, siCisco, siCitrix, siConsul,
  siContainerd, siCurl, siDebian, siDell, siDocker, siElastic, siEnvoyproxy, siEtcd,
  siF5, siFastapi, siFedora, siFlask, siFortinet, siFreebsd, siGit, siGitea, siGithub,
  siGitlab, siGnu, siGradio, siGrafana, siHarbor, siHelm, siHuggingface, siIntel,
  siIstio, siJenkins, siJfrog, siJunipernetworks, siJupyter, siKeycloak, siKong,
  siKubernetes, siLangchain, siLenovo, siLinux, siMariadb, siMeta, siMikrotik, siMinio,
  siMlflow, siMongodb, siMysql, siNginx, siNvidia, siOllama, siOnnx,
  siOpencontainersinitiative, siOpennebula, siOpenssl, siOpenstack, siPaloaltonetworks,
  siPfsense, siPodman, siPostgresql, siPrometheus, siProxmox, siPytorch, siQemu,
  siBentoml, siClickhouse, siFluentbit, siJetbrains, siOpenvpn, siVirtualbox,
  siWireguard, siTailscale,
  siRabbitmq, siRancher, siRay, siRedhat, siRedis, siRockylinux, siSonicwall,
  siStreamlit, siSuse, siSupermicro, siTensorflow, siTraefikproxy, siUbuntu, siVault,
  siVeeam, siVllm, siVmware,
} from "simple-icons";

export type Vendor = { name: string; icon?: SimpleIcon };

/**
 * Ordered: the first pattern that matches the component string wins, so
 * "NVIDIA ... Linux kernel module" resolves to NVIDIA, not Linux.
 */
const VENDORS: Array<[RegExp, string, SimpleIcon?]> = [
  [/nvidia|cuda|triton|vgpu|dgx|nemo|tensorrt|megatron|dynamo|nvlddmkm|gpu display driver|container toolkit|gpu operator|nccl|cudnn|nvjpeg|falcon|jetson|mellanox|connectx|bluefield|doca|nvswitch|nvshmem|\bmig\b|gb10|gb200|chatrtx|geforce/i, "NVIDIA", siNvidia],
  [/supermicro/i, "Supermicro", siSupermicro],
  [/dell|idrac|poweredge/i, "Dell", siDell],
  [/hewlett|hpe|\bilo\b|proliant/i, "HPE"],
  [/lenovo|xclarity/i, "Lenovo", siLenovo],
  [/\bami\b|megarac/i, "AMI"],
  [/kubernetes|kube-|kubelet|kubectl/i, "Kubernetes", siKubernetes],
  [/nginx/i, "NGINX", siNginx],
  [/docker|moby|buildkit/i, "Docker", siDocker],
  [/containerd/i, "containerd", siContainerd],
  [/podman/i, "Podman", siPodman],
  [/runc|cri-o|crio|open container/i, "OCI", siOpencontainersinitiative],
  [/kata/i, "Kata Containers"],
  [/cilium/i, "Cilium", siCilium],
  [/calico|tigera/i, "Calico"],
  [/argo/i, "Argo", siArgo],
  [/envoy/i, "Envoy", siEnvoyproxy],
  [/istio/i, "Istio", siIstio],
  [/traefik/i, "Traefik", siTraefikproxy],
  [/rancher/i, "Rancher", siRancher],
  [/helm/i, "Helm", siHelm],
  [/harbor/i, "Harbor", siHarbor],
  [/kubevirt/i, "KubeVirt"],
  [/slurm/i, "Slurm"],
  [/redis|valkey/i, "Redis", siRedis],
  [/minio/i, "MinIO", siMinio],
  [/grafana|loki/i, "Grafana", siGrafana],
  [/prometheus/i, "Prometheus", siPrometheus],
  [/vmware|esxi|vcenter|vsphere/i, "VMware", siVmware],
  [/palo alto|pan-os|globalprotect/i, "Palo Alto Networks", siPaloaltonetworks],
  [/citrix|netscaler|xenserver/i, "Citrix", siCitrix],
  [/gitlab/i, "GitLab", siGitlab],
  [/github/i, "GitHub", siGithub],
  [/gitea/i, "Gitea", siGitea],
  [/jupyter/i, "Jupyter", siJupyter],
  [/pytorch|torchserve|libtorch|\btorch\b/i, "PyTorch", siPytorch],
  [/tensorflow|keras|tf serving/i, "TensorFlow", siTensorflow],
  [/gradio/i, "Gradio", siGradio],
  [/mlflow/i, "MLflow", siMlflow],
  [/kuberay|\bray\b/i, "Ray", siRay],
  [/vllm/i, "vLLM", siVllm],
  [/hugging ?face|transformers|safetensors|text generation inference/i, "Hugging Face", siHuggingface],
  [/ollama/i, "Ollama", siOllama],
  [/langchain/i, "LangChain", siLangchain],
  [/llama[ .-]?cpp/i, "llama.cpp"],
  [/streamlit/i, "Streamlit", siStreamlit],
  [/onnx/i, "ONNX", siOnnx],
  [/fastapi/i, "FastAPI", siFastapi],
  [/flask/i, "Flask", siFlask],
  [/meta\b|llama stack/i, "Meta", siMeta],
  [/ubuntu|canonical/i, "Ubuntu", siUbuntu],
  [/debian/i, "Debian", siDebian],
  [/red ?hat|rhel|openshift/i, "Red Hat", siRedhat],
  [/suse/i, "SUSE", siSuse],
  [/rocky linux/i, "Rocky Linux", siRockylinux],
  [/almalinux/i, "AlmaLinux", siAlmalinux],
  [/alpine/i, "Alpine Linux", siAlpinelinux],
  [/centos/i, "CentOS", siCentos],
  [/fedora/i, "Fedora", siFedora],
  [/freebsd/i, "FreeBSD", siFreebsd],
  [/intel|xeon|\bsgx\b/i, "Intel", siIntel],
  [/\bamd\b|epyc|ryzen|rocm/i, "AMD", siAmd],
  [/\barm\b|cortex/i, "Arm", siArm],
  [/cisco/i, "Cisco", siCisco],
  [/juniper|junos/i, "Juniper", siJunipernetworks],
  [/broadcom/i, "Broadcom", siBroadcom],
  [/fortinet|fortigate|fortios/i, "Fortinet", siFortinet],
  [/\bf5\b|big-ip/i, "F5", siF5],
  [/sonicwall/i, "SonicWall", siSonicwall],
  [/mikrotik/i, "MikroTik", siMikrotik],
  [/pfsense/i, "pfSense", siPfsense],
  [/etcd/i, "etcd", siEtcd],
  [/ceph/i, "Ceph", siCeph],
  [/postgres/i, "PostgreSQL", siPostgresql],
  [/mysql/i, "MySQL", siMysql],
  [/mariadb/i, "MariaDB", siMariadb],
  [/mongodb/i, "MongoDB", siMongodb],
  [/elastic|kibana|logstash/i, "Elastic", siElastic],
  [/kafka/i, "Apache Kafka", siApachekafka],
  [/tomcat/i, "Apache Tomcat", siApachetomcat],
  [/apache/i, "Apache", siApache],
  [/rabbitmq/i, "RabbitMQ", siRabbitmq],
  [/keycloak/i, "Keycloak", siKeycloak],
  [/kong/i, "Kong", siKong],
  [/jfrog|artifactory/i, "JFrog", siJfrog],
  [/jenkins/i, "Jenkins", siJenkins],
  [/ansible/i, "Ansible", siAnsible],
  [/vault/i, "Vault", siVault],
  [/consul/i, "Consul", siConsul],
  [/openssl/i, "OpenSSL", siOpenssl],
  [/\bcurl\b/i, "curl", siCurl],
  [/glibc|\bgnu\b/i, "GNU", siGnu],
  [/qemu/i, "QEMU", siQemu],
  [/proxmox/i, "Proxmox", siProxmox],
  [/openstack/i, "OpenStack", siOpenstack],
  [/opennebula/i, "OpenNebula", siOpennebula],
  [/veeam/i, "Veeam", siVeeam],
  [/sigstore|cosign|fulcio|rekor/i, "Sigstore"],
  [/firecracker/i, "Firecracker"],
  [/hyper-v|microsoft/i, "Microsoft"],
  [/picklescan/i, "picklescan"],
  [/zabbix/i, "Zabbix"],
  [/gvisor/i, "gVisor"],
  [/n-able|n-central/i, "N-able"],
  [/nagios/i, "Nagios"],
  [/\bsudo\b/i, "sudo"],
  [/jetbrains|teamcity/i, "JetBrains", siJetbrains],
  [/ivanti/i, "Ivanti"],
  [/connectwise|screenconnect/i, "ConnectWise"],
  [/openvpn/i, "OpenVPN", siOpenvpn],
  [/wireguard/i, "WireGuard", siWireguard],
  [/tailscale/i, "Tailscale", siTailscale],
  [/bentoml/i, "BentoML", siBentoml],
  [/fluent bit|fluentd/i, "Fluent", siFluentbit],
  [/litellm/i, "LiteLLM"],
  [/aspeed|ast2[456]00/i, "ASPEED"],
  [/\bkvm\b/i, "KVM"],
  [/clickhouse/i, "ClickHouse", siClickhouse],
  [/samba/i, "Samba"],
  [/\bxen\b/i, "Xen"],
  [/\btpm\b/i, "TPM"],
  [/virtualbox/i, "VirtualBox", siVirtualbox],
  [/oracle/i, "Oracle"],
  [/grub/i, "GNU GRUB", siGnu],
  [/gigabyte/i, "Gigabyte"],
  [/asus/i, "ASUS"],
  [/msi\b/i, "MSI"],
  [/clearml/i, "ClearML"],
  [/localai/i, "LocalAI"],
  [/openssh|\bssh\b/i, "OpenSSH"],
  [/comfyui/i, "ComfyUI"],
  [/stable diffusion|automatic1111|invokeai/i, "Stable Diffusion"],
  [/\bgit\b/i, "Git", siGit],
  [/linux|\bkernel\b/i, "Linux", siLinux],
];

const cache = new Map<string, Vendor>();

export function vendorFor(component: string): Vendor {
  const hit = cache.get(component);
  if (hit) return hit;
  let v: Vendor = { name: component.split(/[\s(/,:]+/)[0] || "?" };
  for (const [re, name, icon] of VENDORS) {
    if (re.test(component)) { v = { name, icon }; break; }
  }
  cache.set(component, v);
  return v;
}
