import type { SimpleIcon } from "simple-icons";
import {
  siAlmalinux, siAlpinelinux, siAmd, siAnsible, siApache, siApachekafka, siApachetomcat,
  siArgo, siArm, siBroadcom, siCentos, siCeph, siCilium, siCisco, siCitrix, siConsul,
  siContainerd, siCoreboot, siCurl, siDebian, siDell, siDocker, siElastic, siEnvoyproxy,
  siEtcd, siF5, siFastapi, siFedora, siFlask, siFortinet, siFreebsd, siGit, siGitea,
  siGithub, siGitlab, siGnu, siGradio, siGrafana, siHarbor, siHashicorp, siHelm,
  siHuggingface, siIntel, siIstio, siJenkins, siJfrog, siJunipernetworks, siJupyter,
  siKeycloak, siKong, siKubernetes, siLangchain, siLenovo, siLinux, siMariadb, siMeta,
  siMikrotik, siMilvus, siMinio, siMlflow, siMongodb, siMysql, siNetdata, siNewrelic,
  siNginx, siNvidia, siOllama, siOnnx, siOpencontainersinitiative, siOpennebula,
  siOpenssl, siOpenstack, siOpentelemetry, siOpenzfs, siPaloaltonetworks, siPfsense,
  siPodman, siPostgresql, siPrometheus, siProxmox, siPython, siPytorch, siQdrant,
  siQemu, siRabbitmq, siRancher, siRay, siRedhat, siRedis, siRockylinux, siSamsung,
  siScikitlearn, siSnyk, siSonatype, siSonicwall, siStreamlit, siSuse, siSupermicro,
  siTensorflow, siTerraform, siTraefikproxy, siTrendmicro, siUbuntu, siVault, siVeeam,
  siVllm, siVmware, siWeightsandbiases,
  siBentoml, siClickhouse, siFluentbit, siJetbrains, siOpenvpn, siVirtualbox,
  siWireguard, siTailscale,
} from "simple-icons";
export type Vendor = { name: string; icon?: SimpleIcon; domain?: string; generic?: boolean };

export function vendorSlug(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}

/**
 * Ordered: the first pattern that matches the component string wins, so
 * "NVIDIA ... Linux kernel module" resolves to NVIDIA, not Linux.
 * Third element is a simple-icons mark; fourth is a domain whose favicon
 * scripts/fetch_vendor_icons.mjs downloads into web/public/vendors/.
 */
const VENDORS: Array<[RegExp, string, SimpleIcon?, string?]> = [
  [/nvidia|cuda|triton|vgpu|dgx|nemo|tensorrt|megatron|dynamo|nvlddmkm|gpu display driver|container toolkit|gpu operator|nccl|cudnn|nvjpeg|falcon|jetson|mellanox|connectx|bluefield|doca|nvswitch|nvshmem|\bmig\b|gb10|gb200|chatrtx|geforce|isaac|omniverse|nvtiff|\bufm\b|rapids|\bigx\b|nsight|dcgm|nvdebug|nvtabular|base command|aistore|\bais\b|snap-4|\bapex\b|hopper|blackwell|\bkai\b/i, "NVIDIA", siNvidia],
  [/supermicro/i, "Supermicro", siSupermicro],
  [/dell|idrac|poweredge/i, "Dell", siDell],
  [/hewlett|hpe|\bilo\b|proliant/i, "HPE", undefined, "hpe.com"],
  [/aruba/i, "Aruba", undefined, "arubanetworks.com"],
  [/lenovo|xclarity/i, "Lenovo", siLenovo],
  [/\bami\b|megarac/i, "AMI", undefined, "ami.com"],
  [/insyde/i, "Insyde", undefined, "insyde.com"],
  [/\bedk\b|tianocore/i, "TianoCore", undefined, "tianocore.org"],
  [/phoenix/i, "Phoenix Technologies", undefined, "phoenix.com"],
  [/aspeed|ast2[456]00/i, "ASPEED", undefined, "aspeedtech.com"],
  [/openbmc/i, "OpenBMC", undefined, "openbmc.org"],
  [/\buefi\b/i, "UEFI Forum", undefined, "uefi.org"],
  [/dmtf|redfish/i, "DMTF", undefined, "dmtf.org"],
  [/\btpm\b|tpm2|libtpms|swtpm/i, "Trusted Computing Group", undefined, "trustedcomputinggroup.org"],
  [/coreboot/i, "coreboot", siCoreboot],
  [/u-boot/i, "U-Boot", undefined, "docs.u-boot.org"],
  [/kubernetes|kube-|kubelet|kubectl|csi-driver|secrets-store|\bcni\b/i, "Kubernetes", siKubernetes],
  [/nginx/i, "NGINX", siNginx],
  [/docker|moby|buildkit|buildah/i, "Docker", siDocker],
  [/containerd/i, "containerd", siContainerd],
  [/podman/i, "Podman", siPodman],
  [/runc|cri-o|crio|open container/i, "OCI", siOpencontainersinitiative],
  [/kata/i, "Kata Containers", undefined, "katacontainers.io"],
  [/gvisor/i, "gVisor", undefined, "gvisor.dev"],
  [/firecracker/i, "Firecracker", undefined, "firecracker-microvm.github.io"],
  [/kubevirt/i, "KubeVirt", undefined, "kubevirt.io"],
  [/cilium/i, "Cilium", siCilium],
  [/calico|tigera/i, "Calico", undefined, "tigera.io"],
  [/argo/i, "Argo", siArgo],
  [/envoy/i, "Envoy", siEnvoyproxy],
  [/istio/i, "Istio", siIstio],
  [/traefik/i, "Traefik", siTraefikproxy],
  [/rancher/i, "Rancher", siRancher],
  [/helm/i, "Helm", siHelm],
  [/harbor/i, "Harbor", siHarbor],
  [/slurm/i, "Slurm", undefined, "schedmd.com"],
  [/kubeflow/i, "Kubeflow", undefined, "kubeflow.org"],
  [/kserve/i, "KServe", undefined, "kserve.github.io"],
  [/cert-manager/i, "cert-manager", undefined, "cert-manager.io"],
  [/headlamp/i, "Headlamp", undefined, "headlamp.dev"],
  [/redis|valkey/i, "Redis", siRedis],
  [/minio/i, "MinIO", siMinio],
  [/grafana|loki/i, "Grafana", siGrafana],
  [/prometheus/i, "Prometheus", siPrometheus],
  [/opentelemetry/i, "OpenTelemetry", siOpentelemetry],
  [/netdata/i, "Netdata", siNetdata],
  [/vmware|esxi|vcenter|vsphere/i, "VMware", siVmware],
  [/\bkvm\b/i, "KVM", undefined, "linux-kvm.org"],
  [/\bxen\b/i, "Xen", undefined, "xenproject.org"],
  [/libvirt/i, "libvirt", undefined, "libvirt.org"],
  [/palo alto|pan-os|globalprotect/i, "Palo Alto Networks", siPaloaltonetworks],
  [/citrix|netscaler|xenserver/i, "Citrix", siCitrix],
  [/gitlab/i, "GitLab", siGitlab],
  [/github/i, "GitHub", siGithub],
  [/gitea/i, "Gitea", siGitea],
  [/jupyter|nbconvert/i, "Jupyter", siJupyter],
  [/pytorch|torchserve|torchvision|libtorch|\btorch\b/i, "PyTorch", siPytorch],
  [/tensorflow|keras|tf serving/i, "TensorFlow", siTensorflow],
  [/scikit-learn|sklearn|skops/i, "scikit-learn", siScikitlearn],
  [/gradio/i, "Gradio", siGradio],
  [/mlflow/i, "MLflow", siMlflow],
  [/kuberay|\bray\b/i, "Ray", siRay],
  [/vllm/i, "vLLM", siVllm],
  [/sglang/i, "SGLang", undefined, "sglang.ai"],
  [/llama[ .-]?cpp|llama-server|stable-diffusion\.cpp|\bggml\b/i, "llama.cpp", undefined, "ggml.ai"],
  [/hugging ?face|transformers|safetensors|text generation inference|diffusers/i, "Hugging Face", siHuggingface],
  [/ollama/i, "Ollama", siOllama],
  [/langchain/i, "LangChain", siLangchain],
  [/llamaindex|llama-index/i, "LlamaIndex", undefined, "llamaindex.ai"],
  [/litellm/i, "LiteLLM", undefined, "litellm.ai"],
  [/localai/i, "LocalAI", undefined, "localai.io"],
  [/openllm|bentoml/i, "BentoML", siBentoml],
  [/streamlit/i, "Streamlit", siStreamlit],
  [/onnx/i, "ONNX", siOnnx],
  [/openvino|intel|xeon|\bsgx\b/i, "Intel", siIntel],
  [/fastapi/i, "FastAPI", siFastapi],
  [/flask/i, "Flask", siFlask],
  [/meta\b|llama stack/i, "Meta", siMeta],
  [/wandb|weights\s*&/i, "Weights & Biases", siWeightsandbiases],
  [/clearml/i, "ClearML", undefined, "clear.ml"],
  [/dagster/i, "Dagster", undefined, "dagster.io"],
  [/comfyui/i, "ComfyUI"],
  [/stable diffusion|automatic1111|invokeai/i, "Stable Diffusion"],
  [/chroma/i, "Chroma", undefined, "trychroma.com"],
  [/qdrant/i, "Qdrant", siQdrant],
  [/milvus/i, "Milvus", siMilvus],
  [/weaviate/i, "Weaviate", undefined, "weaviate.io"],
  [/picklescan|joblib|\bpickle\b/i, "Python", siPython],
  [/ubuntu|canonical/i, "Ubuntu", siUbuntu],
  [/debian/i, "Debian", siDebian],
  [/red ?hat|rhel|openshift/i, "Red Hat", siRedhat],
  [/suse/i, "SUSE", siSuse],
  [/rocky linux/i, "Rocky Linux", siRockylinux],
  [/almalinux/i, "AlmaLinux", siAlmalinux],
  [/alpine/i, "Alpine Linux", siAlpinelinux],
  [/centos/i, "CentOS", siCentos],
  [/fedora/i, "Fedora", siFedora],
  [/freebsd/i, "FreeBSD", siFreebsd],
  [/\bamd\b|epyc|ryzen|rocm/i, "AMD", siAmd],
  [/ampere/i, "Ampere", undefined, "amperecomputing.com"],
  [/\barm\b|cortex/i, "Arm", siArm],
  [/imagination/i, "Imagination", undefined, "imgtec.com"],
  [/samsung/i, "Samsung", siSamsung],
  [/micron|crucial/i, "Micron", undefined, "micron.com"],
  [/sk hynix|skhynix/i, "SK hynix", undefined, "skhynix.com"],
  [/kioxia/i, "Kioxia", undefined, "kioxia.com"],
  [/solidigm/i, "Solidigm", undefined, "solidigm.com"],
  [/infineon/i, "Infineon", undefined, "infineon.com"],
  [/microchip/i, "Microchip", undefined, "microchip.com"],
  [/cisco/i, "Cisco", siCisco],
  [/juniper|junos/i, "Juniper", siJunipernetworks],
  [/brocade|broadcom/i, "Broadcom", siBroadcom],
  [/marvell|qlogic/i, "Marvell", undefined, "marvell.com"],
  [/arista/i, "Arista", undefined, "arista.com"],
  [/fortinet|fortigate|fortios/i, "Fortinet", siFortinet],
  [/\bf5\b|big-ip/i, "F5", siF5],
  [/\ba10\b/i, "A10 Networks", undefined, "a10networks.com"],
  [/kemp/i, "Kemp", undefined, "kemptechnologies.com"],
  [/sonicwall/i, "SonicWall", siSonicwall],
  [/mikrotik/i, "MikroTik", siMikrotik],
  [/pfsense/i, "pfSense", siPfsense],
  [/microsoft|hyper-v|windows|azure/i, "Microsoft", undefined, "microsoft.com"],
  [/\bibm\b/i, "IBM", undefined, "ibm.com"],
  [/schneider|\bapc\b/i, "Schneider Electric", undefined, "se.com"],
  [/eaton/i, "Eaton", undefined, "eaton.com"],
  [/tripp/i, "Tripp Lite", undefined, "tripplite.com"],
  [/cyberpower/i, "CyberPower", undefined, "cyberpowersystems.com"],
  [/vertiv/i, "Vertiv", undefined, "vertiv.com"],
  [/rittal/i, "Rittal", undefined, "rittal.com"],
  [/raritan/i, "Raritan", undefined, "raritan.com"],
  [/opengear/i, "Opengear", undefined, "opengear.com"],
  [/lantronix/i, "Lantronix", undefined, "lantronix.com"],
  [/moxa/i, "Moxa", undefined, "moxa.com"],
  [/digi\b/i, "Digi", undefined, "digi.com"],
  [/perle/i, "Perle", undefined, "perle.com"],
  [/dataprobe/i, "Dataprobe", undefined, "dataprobe.com"],
  [/sunbird/i, "Sunbird", undefined, "sunbirddcim.com"],
  [/\baten\b/i, "ATEN", undefined, "aten.com"],
  [/etcd/i, "etcd", siEtcd],
  [/ceph/i, "Ceph", siCeph],
  [/lustre/i, "Lustre", undefined, "lustre.org"],
  [/beegfs/i, "BeeGFS", undefined, "beegfs.io"],
  [/weka/i, "WEKA", undefined, "weka.io"],
  [/openzfs|\bzfs\b/i, "OpenZFS", siOpenzfs],
  [/spdk/i, "SPDK", undefined, "spdk.io"],
  [/postgres/i, "PostgreSQL", siPostgresql],
  [/mysql/i, "MySQL", siMysql],
  [/mariadb/i, "MariaDB", siMariadb],
  [/mongodb/i, "MongoDB", siMongodb],
  [/clickhouse/i, "ClickHouse", siClickhouse],
  [/elastic|kibana|logstash/i, "Elastic", siElastic],
  [/kafka/i, "Apache Kafka", siApachekafka],
  [/tomcat/i, "Apache Tomcat", siApachetomcat],
  [/apache/i, "Apache", siApache],
  [/rabbitmq/i, "RabbitMQ", siRabbitmq],
  [/keycloak/i, "Keycloak", siKeycloak],
  [/kong/i, "Kong", siKong],
  [/teleport/i, "Teleport", undefined, "goteleport.com"],
  [/oauth2-proxy/i, "OAuth2 Proxy", undefined, "oauth2-proxy.github.io"],
  [/jfrog|artifactory/i, "JFrog", siJfrog],
  [/sonatype|nexus/i, "Sonatype", siSonatype],
  [/jenkins/i, "Jenkins", siJenkins],
  [/ansible/i, "Ansible", siAnsible],
  [/terraform/i, "Terraform", siTerraform],
  [/hashicorp|nomad|packer/i, "HashiCorp", siHashicorp],
  [/vault/i, "Vault", siVault],
  [/consul/i, "Consul", siConsul],
  [/sigstore|cosign|fulcio|rekor/i, "Sigstore", undefined, "sigstore.dev"],
  [/snyk/i, "Snyk", siSnyk],
  [/trend micro|\btrend\b/i, "Trend Micro", siTrendmicro],
  [/acronis/i, "Acronis", undefined, "acronis.com"],
  [/nakivo/i, "NAKIVO", undefined, "nakivo.com"],
  [/veeam/i, "Veeam", siVeeam],
  [/zabbix/i, "Zabbix", undefined, "zabbix.com"],
  [/nagios/i, "Nagios", undefined, "nagios.org"],
  [/n-able|n-central/i, "N-able", undefined, "n-able.com"],
  [/progress|whatsup/i, "Progress", undefined, "progress.com"],
  [/splunk/i, "Splunk"],
  [/new relic/i, "New Relic", siNewrelic],
  [/jetbrains|teamcity/i, "JetBrains", siJetbrains],
  [/ivanti/i, "Ivanti", undefined, "ivanti.com"],
  [/connectwise|screenconnect/i, "ConnectWise", undefined, "connectwise.com"],
  [/portkey/i, "Portkey", undefined, "portkey.ai"],
  [/openvpn/i, "OpenVPN", siOpenvpn],
  [/wireguard/i, "WireGuard", siWireguard],
  [/tailscale/i, "Tailscale", siTailscale],
  [/openssh|\bssh\b/i, "OpenSSH", undefined, "openssh.com"],
  [/openssl/i, "OpenSSL", siOpenssl],
  [/\bsudo\b/i, "sudo", undefined, "sudo.ws"],
  [/\bcurl\b/i, "curl", siCurl],
  [/glibc|\bgnu\b|grub/i, "GNU", siGnu],
  [/qemu/i, "QEMU", siQemu],
  [/proxmox/i, "Proxmox", siProxmox],
  [/openstack/i, "OpenStack", siOpenstack],
  [/opennebula/i, "OpenNebula", siOpennebula],
  [/haproxy/i, "HAProxy", undefined, "haproxy.org"],
  [/samba/i, "Samba", undefined, "samba.org"],
  [/fluent bit|fluentd/i, "Fluent", siFluentbit],
  [/gigabyte/i, "Gigabyte", undefined, "gigabyte.com"],
  [/asus/i, "ASUS"],
  [/msi\b/i, "MSI"],
  [/eurosoft/i, "Eurosoft", undefined, "eurosoft-uk.com"],
  [/cryptopro/i, "CryptoPro", undefined, "cryptopro.ru"],
  [/cz\.nic|turris|knot/i, "CZ.NIC", undefined, "nic.cz"],
  [/virtualbox/i, "VirtualBox", siVirtualbox],
  [/oracle/i, "Oracle", undefined, "oracle.com"],
  [/zyxel/i, "Zyxel"],
  [/\bgit\b/i, "Git", siGit],
  [/polkit|\bpam\b|shadow-utils|libblockdev|lldpd|open-iscsi|tcmu|systemd|\bshim\b|linux|\bkernel\b/i, "Linux", siLinux],
];

const cache = new Map<string, Vendor>();

export function vendorFor(component: string): Vendor {
  const hit = cache.get(component);
  if (hit) return hit;
  let v: Vendor = { name: component.split(/[\s(/,:]+/)[0] || "?", generic: true };
  for (const [re, name, icon, domain] of VENDORS) {
    if (re.test(component)) { v = { name, icon, domain }; break; }
  }
  cache.set(component, v);
  return v;
}

/** Every vendor that relies on a downloaded favicon; consumed by the fetch script. */
export function faviconTargets(): Array<{ slug: string; domain: string }> {
  const seen = new Map<string, string>();
  for (const [, name, icon, domain] of VENDORS) {
    if (!icon && domain) seen.set(vendorSlug(name), domain);
  }
  return [...seen.entries()].map(([slug, domain]) => ({ slug, domain }));
}
